### ISSUE TITLE
Betwixt

### ISSUE THREAD

**Issue by smejia** [qmatic/mobile-example#1]
Hi Gavin
Nice to greet you,
I am reviewing the information that expose in this repository and I'm realizing that no longer make reference to the use of middleware, I wonder if you no longer recommend its use? The architecture  app -middleware-orchestra  remains?

Regards,

**Comment by gavsmi** [comment]
Hi,

The middleware no longer exists. There was no call for it within the market, so it was discontinued and the service taken down.

You would never go app -> Orchestra, as you wouldn't expose Orchestra directly to public networks. In production environments clients would be integrating their existing app backends with Orchestra via the API.

This is just an example of the functionality in the API in the context of an app. It is good for demonstration / learning purposes, but not for production.

**Comment by smejia** [comment]
Ok thanks Mr. Gavin,
If you and I are talking about it, then The middleware that you say, is el Betwixt of node JS that you indicated in the publication of the before version of this example on GitHub?

**Comment by gavsmi** [comment]
Yes, and the middleware service at qmaticbeat.com that Qmatic provided - based on Betwixt, but multi-tenant.
